{% set version = "0.5.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-slickr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/slickR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/slickR/slickR_{{ version }}.tar.gz
  sha256: f7d996fd6d026148c1ad0acbb8c2abb85b343965e8029a19de3c45d87634b2ff

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-htmlwidgets
    - r-lifecycle
    - r-xml2
  run:
    - r-base
    - r-base64enc
    - r-htmltools
    - r-htmlwidgets
    - r-lifecycle
    - r-xml2

test:
  commands:
    - $R -e "library('slickR')"           # [not win]
    - "\"%R%\" -e \"library('slickR')\""  # [win]

about:
  home: https://github.com/metrumresearchgroup/slickR
  license: MIT
  summary: Create and customize interactive carousels using the 'Slick' JavaScript library and the 'htmlwidgets' package. The carousels can contain plots produced in R, images, 'iframes', videos and other 'htmlwidgets'.  These carousels can be created directly from the R console, and viewed in the 'RStudio' internal viewer,
    in Shiny apps and R Markdown documents.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - phue

# Package: slickR
# Title: Create Interactive Carousels with the JavaScript 'Slick' Library
# Version: 0.4.9
# Date: 2020-02-13
# Authors@R: person(given = "Jonathan", family = "Sidi", role = c("aut", "cre"), email = "yonis@metrumrg.com")
# Description: Create and customize interactive carousels using the 'Slick' JavaScript library and the 'htmlwidgets' package. The carousels can contain plots produced in R, images, 'iframes', videos and other 'htmlwidgets'.  These carousels can be created directly from the R console, and viewed in the 'RStudio' internal viewer, in Shiny apps and R Markdown documents.
# License: MIT + file LICENSE
# URL: https://github.com/metrumresearchgroup/slickR
# BugReports: https://github.com/metrumresearchgroup/slickR/issues
# Depends: R (>= 3.5.0)
# Imports: htmltools,utils,tools,lifecycle,stats,xml2,base64enc,htmlwidgets
# Suggests: jsonlite, knitr, pdftools, rmarkdown, svglite, leaflet, testthat, covr
# VignetteBuilder: knitr
# RdMacros: lifecycle
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-02-14 13:09:18 UTC; yonis
# Author: Jonathan Sidi [aut, cre]
# Maintainer: Jonathan Sidi <yonis@metrumrg.com>
# Repository: CRAN
# Date/Publication: 2020-02-14 13:30:02 UTC
